import { expect, test } from "@playwright/test";

const password = process.env.SITE_PASSWORD ?? "LAYCC";

async function login(page: import("@playwright/test").Page) {
  await page.goto("/login");
  await page.getByLabel("Password").fill(password);
  await page.getByRole("button", { name: "Sign in" }).click();
  await expect(page.getByRole("heading", { name: "Roster", exact: true })).toBeVisible();
}

test("unauthenticated visit redirects to login", async ({ page }) => {
  await page.goto("/");
  await expect(page).toHaveURL(/\/login/);
  await expect(page.getByRole("heading", { name: "Look After You" })).toBeVisible();
});

test("login grants access to roster", async ({ page }) => {
  await login(page);
  await expect(page.getByText("Instagram performance across the talent roster.")).toBeVisible();
});

test("influencer page shows overhauled dashboard sections", async ({ page }) => {
  await login(page);

  const firstCard = page.locator('a.card[href^="/influencer/"]').first();
  await expect(firstCard).toBeVisible();
  await firstCard.click();

  await expect(page.getByRole("link", { name: "← Roster" })).toBeVisible();
  await expect(page.getByText("No bio available.")).toHaveCount(0);
  await expect(page.getByRole("heading", { name: "Performance by format" })).toBeVisible();
  await expect(page.getByText(/based on \d+ posts/).first()).toBeVisible();
  await expect(page.getByRole("heading", { name: "Recent posts" })).toBeVisible();
  await expect(page.getByRole("columnheader", { name: "Eng. rate" })).toBeVisible();
});

test("influencer page renders creative recommendations section", async ({ page }) => {
  await login(page);

  const firstCard = page.locator('a.card[href^="/influencer/"]').first();
  await firstCard.click();

  await expect(page.getByRole("heading", { name: "Creative recommendations" })).toBeVisible();
});

test("influencer page renders top performing posts with Instagram links when present", async ({ page }) => {
  await login(page);

  const firstCard = page.locator('a.card[href^="/influencer/"]').first();
  await firstCard.click();

  const heading = page.getByRole("heading", { name: "Top performing posts" });
  await expect(heading).toBeVisible();

  const firstLink = page.getByRole("link", { name: "View on Instagram →" }).first();
  if (await firstLink.isVisible().catch(() => false)) {
    await expect(firstLink).toHaveAttribute("href", /instagram\.com\/p\//);
  }
});

test("influencer detail page renders an avatar next to the handle", async ({ page }) => {
  await login(page);

  const firstCard = page.locator('a.card[href^="/influencer/"]').first();
  await firstCard.click();
  await expect(page.getByRole("link", { name: "← Roster" })).toBeVisible();

  await expect(page.locator("main img, main div.rounded-full").first()).toBeVisible();
});

test("roster page loads without crashing when highlight data exists", async ({ page }) => {
  await login(page);

  await expect(page.getByRole("heading", { name: "Roster", exact: true })).toBeVisible();
  // Attention strip is conditional on live warning-severity highlights existing;
  // just confirm the page renders roster cards regardless.
  await expect(page.locator('a.card[href^="/influencer/"]').first()).toBeVisible();
});

test("roster cards render an avatar for each influencer", async ({ page }) => {
  await login(page);

  const firstCard = page.locator('a.card[href^="/influencer/"]').first();
  await expect(firstCard.locator("img, div.rounded-full").first()).toBeVisible();
});

test("roster page renders roster-wide briefing and toggles language when present", async ({ page }) => {
  await login(page);

  await expect(page.getByRole("heading", { name: "Roster", exact: true })).toBeVisible();

  const briefingHeading = page.getByRole("heading", { name: "This week across the roster" });
  if (await briefingHeading.isVisible().catch(() => false)) {
    const toggle = page.getByRole("button", { name: /^(EN|ES)$/ });
    await expect(toggle).toBeVisible();
    const before = await toggle.textContent();
    await toggle.click();
    await expect(toggle).not.toHaveText(before ?? "");
  } else {
    // Briefing is generated by the scraper's daily run — absent on a fresh DB is fine.
    await expect(page.locator('a.card[href^="/influencer/"]').first()).toBeVisible();
  }
});
