import { expect, test } from "@playwright/test";

const password = process.env.SITE_PASSWORD ?? "LAYCC";

async function login(page: import("@playwright/test").Page) {
  await page.goto("/login");
  await page.getByLabel("Team password").fill(password);
  await page.getByRole("button", { name: "Enter" }).click();
  await expect(page.getByRole("heading", { name: "The Roster", exact: true })).toBeVisible();
}

test("trends page shows big headlines and toggles language when present, else falls back", async ({ page }) => {
  await login(page);
  await page.goto("/trends");

  await expect(page.getByRole("heading", { name: "The Wire" })).toBeVisible();

  const toggle = page.getByRole("button", { name: /^(EN|ES)$/ });
  if (await toggle.isVisible().catch(() => false)) {
    const headline = page.locator("ol li p").first();
    await expect(headline).toBeVisible();
    const before = await headline.textContent();
    await toggle.click();
    await expect(headline).not.toHaveText(before ?? "");
  } else {
    // Headlines are generated by the scraper's daily run — absent on a fresh DB is fine.
    await expect(page.getByText(/No trend data yet|Latest Instagram trend report scrapes/)).toBeVisible();
  }
});
